[package]
name = "zg_graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
zg_layouts = {path = "../zg_layouts"}
zg_pipeline = {path = "../zg_pipeline"}
zg_world = {path = "../zg_world"}
zg_systems = {path = "../zg_systems"}
zg_utils = {path = "../zg_utils"}

wgpu = {workspace = true}
winit = {workspace = true}
anyhow = {workspace = true}
